var breakfast = [
{key:"V00OSTKZWI", name:"Bagel And Cream Cheese", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/pdfGzyp/breakfast1.png", price:9.50},
{key:"P00OSTDZWM", name:"Breakfast sandwich", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/8bJV04d/breakfast2.png", price:18.00},
{key:"B00OCDKZWM", name:"Baked Chiken", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/xjkVyVZ/breakfast3.png", price:30.00},
{key:"B00OSTMKWM", name:"Eggs Benedict", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/GPS1MS0/breakfast4.png", price:8.00},
{key:"B00OSVFZWM", name:"Toast Croissant Fried egg", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/brDv96s/breakfast5.png", price:12.50},
{key:"B00OSTKZNB", name:"Full Breakfast Fried Egg Toast", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/WfVDMQ2/breakfast6.png", price:15.90},
];

export default breakfast;
