var dinner = [
{key:"W00OSTQWER", name:"Bagel And Cream Cheese", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/BsmW04m/dinner1.png", price:10.50},
{key:"U00OSTTYUI", name:"Salmon with grapefruit salad", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/85FdR1G/dinner2.png", price:6.00},
{key:"Y00OSTOPLK", name:"Lemony salmon piccata", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/7CNNcX6/dinner3.png", price:38.00},
{key:"T00OSTJHGF", name:"Pork tenderloin with quinoa", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/JB1JctT/dinner4.png", price:23.00},
{key:"R00OSTDSAZ", key:"P00OSTDZWM", name:"French fries with cheese", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/CBYXsWr/dinner5.png", price:50.00},
{key:"E00OSTXCVB", name:"Garlic butter salmon", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/KV78f0v/dinner6.png", price:9.50},
];

export default dinner;