var lunch = [
{key:"zaq", name:"Healthy Meal Plan", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/F7CKNrj/lunch1.png", price:25.00},
{key:"xsw", name:"Fried chicken bento", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/zGTrGFw/lunch2.png", price:9.00},
{key:"cde", name:"Tarang-Rubbed-Salman", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/prFCj77/lunch3.png", price:24.00},
{key:"vfr", name:"Indian Lunch", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/pX701Bg/lunch4.png", price:8.00},
{key:"bgt", name:"Beef Steak", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/f85H3vz/lunch5.png", price:27.00},
{key:"nhy", name:"Thie Steak", subName:"Lorem Ipsum is simply dummy", details:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining", image:"https://i.ibb.co/Vpf4qPW/lunch6.png", price:32.00},
];

export default lunch;